### ISSUE TITLE
您有没有同花顺金融因果关系的数据集，方便分享下吗

### ISSUE THREAD

**Issue by ahao0328** [YangLock/EventPapersArchive#1]

**Comment by YangLock** [comment]
￼

**Comment by YangLock** [comment]
数据集通过邮件回复发给你了，查收一下

**Comment by ahao0328** [comment]
邮箱里面没有看见 能不能直接发我邮箱，谢谢大佬 ***@***.***

YangLock ***@***.***> 于2024年2月29日周四 16:16写道：

**Comment by YangLock** [comment]
你的邮箱号是什么

**Comment by ahao0328** [comment]
谷歌邮箱： howardchen0328

YangLock ***@***.***> 于2024年2月29日周四 17:35写道：

**Comment by ahao0328** [comment]
***@***.***"写不了 会被屏蔽

Howard Chen ***@***.***> 于2024年2月29日周四 17:39写道：

**Comment by YangLock** [comment]
https://wormhole.app/JqNQX#Kp8ShKhMJHdqMiFTdT9zpg
文件上传到这里了

**Comment by ahao0328** [comment]
感谢！！

YangLock ***@***.***>于2024年2月29日 周四18:54写道：
